/** \brief FUNCION QUE SOLO MUESTRA EL MENU DE OPCIONES
 *
 * \param
 * \param
 * \return NO DEVUELVE DATOS
 *
 */
void menu();

/** \brief FUNCION QUE REALIZA LA SUMA DE DOS VALORES DEL TIPO FLOTANTE
 *
 * \param TOMA LOS VALORES YA INGRESADOS
 * \param LOS SUMA
 * \return DEVUELVE EL RESULTADO DE DICHA SUMA CON VALOR FLOTANTE
 *
 */
float sumar(float a,float b);

/** \brief FUNCION QUE REALIZA LA RESTA DE DOS VALORES DEL TIPO FLOTANTE
 *
 * \param TOMA LOS VALORES YA INGRESADOS
 * \param LOS RESTA
 * \return DEVUELVE EL RESULTADO DE DICHA OPERACION CON VALOR FLOTANTE
 *
 */

float restar(float a,float b);

/** \brief FUNCION QUE REALIZA LA MULTIPLICACION DE DOS VALORES DEL TIPO FLOTANTE
 *
 * \param TOMA LOS VALORES YA INGRESADOS
 * \param LOS MULTIPLICA
 * \return DEVUELVE EL RESULTADO DE DICHA OPERACION CON VALOR FLOTANTE
 *
 */
float multiplicar(float a,float b);

/** \brief FUNCION QUE REALIZA LA DIVISION DE DOS VALORES DEL TIPO FLOTANTE
 *
 * \param TOMA LOS VALORES YA INGRESADOS
 * \param LOS DIVIDE
 * \return DEVUELVE EL RESULTADO DE DICHA OPERACION CON VALOR FLOTANTE
 *
 */
float dividir(float a,float b);

/** \brief FUNCION QUE RESUELVE EL FACTORIAL DE UN SOLO VALOR DEL TIPO DOUBLE
 *
 * \param TOMA EL VALOR INGRESADO
 * \param CALCULA EL FACTORIAL DE DICHO VALOR
 * \return DEVUELVE EL RESULTADO DE DICHA OPERACION CON VALOR DEL TIPO DOUBLE
 *
 */
double factorizar(int a);
