/** \brief FUNCION QUE SOLO MUESTRA EL MENU DE OPCIONES
 *
 * \param
 * \param
 * \return NO DEVUELVE DATOS
 *
 */
void menu();

/** \brief FUNCION QUE REALIZA LA SUMA DE DOS VALORES DEL TIPO FLOTANTE
 *
 * \param TOMA DOS VALORES DEL TIPO FLOTANTE
 * \param OPERA CON LOS VALORES, EN ESTE CASO, LOS SUMA
 * \return DEVUELVE EL RESULTADO DE DICHA SUMA CON VALOR FLOTANTE
 *
 */
float sumar(float a,float b);

/** \brief FUNCION QUE REALIZA LA RESTA DE DOS VALORES DEL TIPO FLOTANTE
 *
 * \param TOMA DOS VALORES DEL TIPO FLOTANTE
 * \param OPERA CON LOS VALORES, EN ESTE CASO, LOS RESTA
 * \return DEVUELVE EL RESULTADO DE DICHA OPERACION CON VALOR FLOTANTE
 *
 */

float restar(float a,float b);

/** \brief FUNCION QUE REALIZA LA MULTIPLICACION DE DOS VALORES DEL TIPO FLOTANTE
 *
 * \param TOMA DOS VALORES DEL TIPO FLOTANTE
 * \param OPERA CON LOS VALORES, EN ESTE CASO, LOS MULTIPLICA
 * \return DEVUELVE EL RESULTADO DE DICHA OPERACION CON VALOR FLOTANTE
 *
 */
float multiplicar(float a,float b);

/** \brief FUNCION QUE REALIZA LA DIVISION DE DOS VALORES DEL TIPO FLOTANTE
 *
 * \param TOMA DOS VALORES DEL TIPO FLOTANTE
 * \param OPERA CON LOS VALORES, EN ESTE CASO, LOS DIVIDE
 * \return DEVUELVE EL RESULTADO DE DICHA OPERACION CON VALOR FLOTANTE
 *
 */
float dividir(float a,float b);

/** \brief FUNCION QUE RESUELVE EL FACTORIAL DE UN SOLO VALOR DEL TIPO FLOTANTE
 *
 * \param TOMA UN VALOR DEL TIPO FLOTANTE
 * \param INICIALIZA UNA VARIABLE DEL TIPO DOUBLE, LA CUAL FUNCIONARA COMO UN ACUMULADOR
 * \param SE OPERA CON EL VALOR FLOTANTE QUE TOMA LA FUNCION, Y CON LA VARIABLE INICIALIZADA DEL TIPO DOUBLE , EN ESTE CASO, SE GUARDARA EN LA VARIABLE DEL TIPO DOUBLE EL PRODUCTO DE LAS MISMAS
 * \param SE ITERA CON EL VALOR FLOTANTE QUE TOMA LA FUNCION CON EL FIN DE QUE VAYA DISMINUYENDO EN 1, Y ASI, PODER ACUMULAR LOS DISTINTOS RESULTADOS EN NUESTRA VARIABLE DEL TIPO DOUBLE
 * \return DEVUELVE EL RESULTADO DE LAS OPERACIONES ACUMULADAS EN LA VARIABLE DEL TIPO DOUBLE
 *
 */
double factorizar(float a);
